### ISSUE TITLE
When opening the React developer tools and pointing to a component using `useForm`, there is an error displaying component properties

### ISSUE THREAD

**Issue by ngbrown** [edmundhung/conform#450]
### Describe the bug and the expected behavior

When using the React Developer Tools (in either FireFox or Chrome), and on the "Components" tab, when navigating to a component that uses the `useForm()` hook, there is an error displayed in the tab about a timeout and in the Console there is an error stack from `@conform-to/dom`.

I would expect the conform proxy to not error out when the React Developer Tools is probing the contents of a component.

### Conform version

v1.0.1

### Steps to Reproduce the Bug or Issue

1. Use the `useForm()` hook in a component.
1. Run in developer mode and view in a browser.
1. Install the [React Developer Tools](https://chromewebstore.google.com/detail/react-developer-tools/fmkadmapgofadopljbjfkapdkoienihi) extension.
1. Open the browsers' Developer tools (`F12`).
1. Open the "Components" tab and navigate to the component where the form is.

### What browsers are you seeing the problem on?

Chrome, Firefox

### Additional context

This is the error that dumps into the console:

```
Uncaught TypeError: name.split is not a function
    at getPaths (formdata.mjs:32:15)
    at form.mjs:105:17
    at Object.get (form.mjs:95:107)
    at getDataType (utils.js:499:1) (webpack://react-devtools-extensions/react-devtools-shared/src/utils.js)
    at dehydrate (hydration.js:75:1)
    at hydration.js:227:1
    at Set.forEach (<anonymous>)
    at dehydrate (hydration.js:225:1)
    at hydration.js:227:1
    at Set.forEach (<anonymous>)
getPaths @ formdata.mjs:32
(anonymous) @ form.mjs:105
get @ form.mjs:95
getDataType @ utils.js:499
dehydrate @ hydration.js:75
(anonymous) @ hydration.js:227
dehydrate @ hydration.js:225
(anonymous) @ hydration.js:227
dehydrate @ hydration.js:225
(anonymous) @ hydration.js:160
dehydrate @ hydration.js:160
(anonymous) @ hydration.js:227
dehydrate @ hydration.js:225
(anonymous) @ hydration.js:160
dehydrate @ hydration.js:160
(anonymous) @ hydration.js:227
dehydrate @ hydration.js:225
(anonymous) @ hydration.js:160
dehydrate @ hydration.js:160
cleanForBridge @ utils.js:26
inspectElement @ renderer.js:3364
(anonymous) @ agent.js:175
emit @ events.js:37
(anonymous) @ bridge.js:136
listener @ backendManager.js:1
postMessage (async)
handleMessageFromDevtools @ proxy.js:1
Show 25 more frames
```

I patched `getPaths(name)` temporarily to find out what type data was being passed and got this:

```
backendManager.js:1 typeof name === 'symbol' Symbol(Symbol.iterator)
backendManager.js:1 typeof name === 'symbol' Symbol(Symbol.toStringTag)
```

This is a snippet of the code that the React Developer Tools is running when it hits the error:

```js
    case 'object':
      if (src_isArray(data)) {
        return 'array';
      } else if (ArrayBuffer.isView(data)) {
        return utils_hasOwnProperty.call(data.constructor, 'BYTES_PER_ELEMENT') ? 'typed_array' : 'data_view';
      } else if (data.constructor && data.constructor.name === 'ArrayBuffer') {
        // HACK This ArrayBuffer check is gross; is there a better way?
        // We could try to create a new DataView with the value.
        // If it doesn't error, we know it's an ArrayBuffer,
        // but this seems kind of awkward and expensive.
        return 'array_buffer';
      } else if (typeof data[Symbol.iterator] === 'function') {
        const iterator = data[Symbol.iterator]();

        if (!iterator) {// Proxies might break assumptoins about iterators.
          // See github.com/facebook/react/issues/21654
        } else {
          return iterator === data ? 'opaque_iterator' : 'iterator';
        }
      } else if (data.constructor && data.constructor.name === 'RegExp') {
        return 'regexp';
      } else {
        // $FlowFixMe[method-unbinding]
        const toStringValue = Object.prototype.toString.call(data); // Symbol.toStringTag

        if (toStringValue === '[object Date]') {
          return 'date';
        } else if (toStringValue === '[object HTMLAllCollection]') {
          return 'html_all_collection';
        }
      }

      if (!isPlainObject(data)) {
        return 'class_instance';
      }

      return 'object';
```

**Comment by ngbrown** [comment]
I used `patch-package` to fix the problem for myself:

```diff
diff --git a/node_modules/@conform-to/dom/formdata.js b/node_modules/@conform-to/dom/formdata.js
index 3026f5c..ec67082 100644
--- a/node_modules/@conform-to/dom/formdata.js
+++ b/node_modules/@conform-to/dom/formdata.js
@@ -33,6 +33,9 @@ function getPaths(name) {
   if (!name) {
     return [];
   }
+  if (typeof name === "symbol") {
+    return [];
+  }
   return name.split(/\.|(\[\d*\])/).reduce((result, segment) => {
     if (typeof segment !== 'undefined' && segment !== '') {
       if (segment.startsWith('[') && segment.endsWith(']')) {
diff --git a/node_modules/@conform-to/dom/formdata.mjs b/node_modules/@conform-to/dom/formdata.mjs
index afe2cea..f358b93 100644
--- a/node_modules/@conform-to/dom/formdata.mjs
+++ b/node_modules/@conform-to/dom/formdata.mjs
@@ -29,6 +29,9 @@ function getPaths(name) {
   if (!name) {
     return [];
   }
+  if (typeof name === "symbol") {
+    return [];
+  }
   return name.split(/\.|(\[\d*\])/).reduce((result, segment) => {
     if (typeof segment !== 'undefined' && segment !== '') {
       if (segment.startsWith('[') && segment.endsWith(']')) {
```
